OBM/Models/Organizer.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace OBM.Models
{
    public partial class Organizer
    {
        [StringLength(128)]
        public string organizerName { get; set; }

        public string organizerID { get; set; }
    }
}

OBM/Models/ViewModels/OrganizerViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using OBM.DAL;

namespace OBM.Models.ViewModels
{
    public class OrganizerViewModel
    {
        private EventContext db = new EventContext();

        public OrganizerViewModel(Organizer Org)
        {
            organizer = Org;
            var hasEvents = db.Events.Where(x => x.OrganizerID == Org.organizerID).Count() != 0;
            var temp = new List<Tuple<string, string, int, int>>();
            if (!hasEvents)
            {
                Tuple<string, string, int, int> eventNameLocationCompCountEventIDs = new Tuple<string, string, int, int>("No Events", "", 0, 0);
                temp.Add(eventNameLocationCompCountEventIDs);
            }
            else
            {
                foreach (var _event in db.Events.Where(x => x.OrganizerID == Org.organizerID).ToList())
                {
                    int count = _event.Competitors.Count();
                    var eventNameLocationCompCountEventIDs = new Tuple<string, string, int, int>(_event.EventName, _event.Location, count, _event.EventID);

                    temp.Add(eventNameLocationCompCountEventIDs);
                }
            }
            ListEventNameLocationCompCountEventIDs = temp;
        }
        public Organizer organizer { get; set; }

        public List<Tuple<string, string, int, int>> ListEventNameLocationCompCountEventIDs { get; set; }
    }
}

OBM/Controllers/EventsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Security.Claims;
using System.Web;
using System.Diagnostics;
using System.Web.Mvc;
using Newtonsoft.Json;
using OBM.DAL;
using OBM.Models;
using OBM.Models.ViewModels;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;
using Newtonsoft.Json.Linq;
using System.Net.Http;
using System.IO;
using static MoreLinq.Extensions.MaxByExtension;
using static MoreLinq.Extensions.MinByExtension;
using Microsoft.Ajax.Utilities;
using Ganss.XSS;


namespace OBM.Controllers
{

    public class EventsController : Controller
    {
        private EventContext db = new EventContext();
        HtmlSanitizer sani = new HtmlSanitizer();

        // GET: Events
        public ActionResult Index()
        {
            var eventViewList = new List<EventViewModel>();
            foreach (var i in db.Events.ToList())
            {
                if (i.Public == true)
                    eventViewList.Add(new EventViewModel(i, HttpContext.GetOwinContext().Get<ApplicationUserManager>().FindById(@i.OrganizerID).UserName));
            }
            return View(eventViewList);
        }

        public ActionResult Manage(int? id)
        {
            if (id == null)
            {
                throw new HttpException(400, "Bad Request");
            }
            var eventView = new EventViewModel(db.Events.Find(id), HttpContext.GetOwinContext().Get<ApplicationUserManager>().FindById(db.Events.Find(id).OrganizerID).UserName);
            if (eventView == null)
            {
                throw new HttpException(404, "Page not Found");
            }
            if ((Request.IsAuthenticated && (User.Identity.GetUserId() == eventView.OrganizerID)))
            {
                ViewBag.Access = true;
            }
            else
                ViewBag.Access = false;

            return View(eventView);
        }

        public ActionResult HiddenMatches(int? id)
        {
            if (id == null)
            {
                throw new HttpException(400, "Bad Request");
            }
            var eventView = new EventViewModel(db.Events.Find(db.Tournaments.Find(id).EventID), HttpContext.GetOwinContext().Get<ApplicationUserManager>().FindById(db.Events.Find(db.Tournaments.Find(id).EventID).OrganizerID).UserName);
            if (eventView == null)
            {
                throw new HttpException(404, "Page not Found");
            }
            if ((Request.IsAuthenticated && (User.Identity.GetUserId() == eventView.OrganizerID)))
            {
                ViewBag.Access = true;
            }
            else
                ViewBag.Access = false;
            ViewBag.TournamentID = id;
            return View(eventView);
        }
        public ActionResult StreamHelp()
        {
            return View();
        }

        [HttpGet]
        public String PublicEvents()
        {
            var eventsDb = db.Events.Where(x => x.Public).Select(x => new { x.EventID, x.EventName, x.Description, x.Location, url = ("/Events/Details/" + x.EventID) }).ToList();
            var jsonResponse = new JArray();
            var mylist = new List<Object>();

            foreach (var tempevent in eventsDb)
            {
                var organizerId = db.Events.Find(tempevent.EventID).OrganizerID;
                var organizerName = db.AspNetUsers.Find(organizerId).UserName;

                var tempJson = JObject.FromObject(tempevent);
                tempJson.Add("UserName", organizerName);

                jsonResponse.Add(tempJson);

                mylist.Add(new { tempevent.EventID, tempevent.EventName, tempevent.Description, tempevent.Location, UserName = organizerName, url = ("/Events/Details/" + tempevent.EventID) });
            }


            Debug.WriteLine(jsonResponse);



            var result = JsonConvert.SerializeObject(mylist);


            result.Replace('[', '{');
            result.Replace(']', '}');
            return result;
        }

        // GET: Events/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                throw new HttpException(400, "Bad Request");
            }
            var eventView = new EventViewModel(db.Events.Find(id), HttpContext.GetOwinContext().Get<ApplicationUserManager>().FindById(db.Events.Find(id).OrganizerID).UserName);
            if (eventView == null)
            {
                throw new HttpException(404, "Page not Found");
            }
            if ((eventView.Public == true) || (Request.IsAuthenticated && (User.Identity.GetUserId() == eventView.OrganizerID)))
            {
                ViewBag.Access = true;
            }
            else
                ViewBag.Access = false;

            return View(eventView);
        }

        // GET: Events/Create
        public ActionResult Create()
        {
            ViewBag.OrganizerID = User.Identity.GetUserId();
            return View();
        }

        // POST: Events/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "EventID,OrganizerID,EventName,Description,Location,Public")] Event @event)
        {
            if (ModelState.IsValid)
            {
                db.Events.Add(@event);
                db.SaveChanges();
                return RedirectToAction("Index", "Home");
            }
            ViewBag.OrganizerID = User.Identity.GetUserId();
            return View(@event);
        }

        // GET: Events/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                throw new HttpException(400, "Bad Request");
            }
            Event @event = db.Events.Find(id);
            if (@event == null)
            {
                throw new HttpException(404, "Page not Found");
            }
            if ((Request.IsAuthenticated && (User.Identity.GetUserId() == @event.OrganizerID)))
            {
                ViewBag.Access = true;
            }
            else
                ViewBag.Access = false;
            ViewBag.OrganizerID = User.Identity.GetUserId();
            return View(@event);
        }

        // POST: Events/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "EventID,OrganizerID,EventName,Description,Location,Public")] Event @event)
        {
            if (ModelState.IsValid)
            {
                db.Entry(@event).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            if ((Request.IsAuthenticated && (User.Identity.GetUserId() == @event.OrganizerID)))
            {
                ViewBag.Access = true;
            }
            else
                ViewBag.Access = false;
            return View(@event);
        }

        // GET: Events/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                throw new HttpException(400, "Bad Request");
            }
            Event @event = db.Events.Find(id);
            if (@event == null)
            {
                throw new HttpException(404, "Page not Found");
            }
            if ((Request.IsAuthenticated && (User.Identity.GetUserId() == @event.OrganizerID)))
            {
                ViewBag.Access = true;
            }
            else
                ViewBag.Access = false;
            return View(@event);
        }

        // POST: Events/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Event @event = db.Events.Find(id);
            db.Events.Remove(@event);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult ResponsiveEvents(String search)
        {
            ViewBag.search = search;
            return View();
        }

        [HttpGet]
        public JsonResult EventList(String location, String name)   //ONCE AN EVENT DATE IS PROPERLY IMPLEMENTED IN THE DATABASE, IT WILL BE USED TO SORT THE RESULTS OF THESE QUERIES (.Orderby(x=>x.DateTime))
        {
            Debug.WriteLine(location, name);

            List<Event> eventList = new List<Event>();
            JArray TournamentList = new JArray();

            Debug.WriteLine("LOCATION IS: " + location);
            Debug.WriteLine("NAME IS: " + name);
            if (location != null && location != "")// if we know the location of event, get the events at the location
            {
                foreach (var i in db.Events.Where(p => p.Public && p.Location.Contains(location)).ToList())
                {
                    eventList.Add(i);
                }
            }

            else// if the event field is null, or empty, return all events
            {
                foreach (var i in db.Events.Where(p => p.Public).ToList())
                {
                    eventList.Add(i);
                }
            }

            //NOW THE SEARCH BY NAME
            if (name != null && name != "")
            {
                var eventListTemp = new List<Event>(eventList);
                foreach (var i in eventListTemp)

OBM/Controllers/OrganizerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OBM.DAL;
using OBM.Models;
using OBM.Models.ViewModels;

namespace OBM.Controllers
{
    public class OrganizerController : Controller
    {
        EventContext db = new EventContext();
        // GET: Organizer
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult OrganizersSearch()
        {
            List<Organizer> organizers = new List<Organizer>();

            foreach(var user in db.AspNetUsers)
            {
                Organizer organizer = new Organizer();

                organizer.organizerName = user.UserName;
                organizer.organizerID = user.Id;

                organizers.Add(organizer);
            }

            return View(organizers);
        }

        [HttpGet]
        public ActionResult PublicProfile(string OrgID)
        {
            Organizer organizer = new Organizer();

            organizer.organizerID = OrgID;
            organizer.organizerName = db.AspNetUsers.Find(OrgID).UserName;

            OrganizerViewModel organizerViewModel = new OrganizerViewModel(organizer);

            return View(organizerViewModel);
        }
    }
}

OBM/Views/Organizer/OrganizersSearch.cshtml
@model IEnumerable<OBM.Models.Organizer>
@{
    ViewBag.Title = "Organziser Search";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container-fluid justify-content-center">
    <div class="row">
        <div class="col-12 text-center">
            <h2>Which Organizer are you looking for?</h2>
        </div>
    </div>
    <div class="row justify-content-center">
        <div class="col-4">
            <div class="card bg-secondary">
                <div class="card-body darker">
                    <table id="organizerList" class="table table-responsive-md table-dark table-striped table-hover">
                        <thead>
                            <tr>
                                <th scope="col">
                                    Organizer Name
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach(var organizer in Model)
                            {
                                <tr>
                                    <td>
                                        @Html.ActionLink(organizer.organizerName, "PublicProfile", "Organizer", new { OrgID = organizer.organizerID}, new { @class = "eventdata" })
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

@Scripts.Render("~/bundles/OrganizerSearch")

OBM/Views/Organizer/PublicProfile.cshtml
@model OBM.Models.ViewModels.OrganizerViewModel
@{
    ViewBag.Title = "Profile";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

    <div class="container-fluid">
        <div class="row">
            <div class="col d-flex justify-content-center">
                <h2>@Model.organizer.organizerName</h2>
            </div>
        </div>
        @if (Model.ListEventNameLocationCompCountEventIDs[0].Item1 != "No Events")
        {
            <div class="row d-flex justify-content-center">
                <div class="col-6">
                    <div class="card bg-secondary">
                        <div class="card-body darker">
                            <table id="organizerList" class="table table-responsive-md table-dark table-striped table-hover">
                                <thead>
                                    <tr>
                                        <th scope="col">
                                            Event Name
                                        </th>
                                        <th scope="col">
                                            Competitor Count
                                        </th>
                                        <th scope="col">
                                            Event Location
                                        </th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var _event in Model.ListEventNameLocationCompCountEventIDs)
                                    {
                                        <tr>
                                            <td>
                                                @Html.ActionLink(_event.Item1, "Details", "Events", new { id = _event.Item4 }, new { @class = "eventdata" })
                                            </td>
                                            <td>
                                                @_event.Item3
                                            </td>
                                            <td>
                                                @_event.Item2
                                            </td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        }
        else
        {
           <div class="row">
               <div class="col">
                   <h3><i>@Model.organizer.organizerName has no events yet.</i></h3>
               </div>
           </div>
        }

    </div>
@Scripts.Render("~/bundles/OrganizerSearch")